import '/Javascript_global/Global_settings/jquery-3.6.3.js'
import '/Javascript_global/Global_settings/variables.js'
import '/Javascript_global/Stylizing/buttons.js'
import '/Javascript_global/Stylizing/invert_color.js'
import '/Javascript_global/Stylizing/language.js'
import '/Javascript_global/Stylizing/popover.js'